# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0003_join'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join',
            new_name='JoinHood',
        ),
    ]
