# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0006_auto_20180808_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='location',
            new_name='hood',
        ),
    ]
